//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace BundlingTest {
    
    
    public partial class DemoWebControl {
        
        /// <summary>
        /// StyleBundle1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Bundling.Extensions.Controls.StyleBundle StyleBundle1;
        
        /// <summary>
        /// ScriptBundle1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Bundling.Extensions.Controls.ScriptBundle ScriptBundle1;
        
        /// <summary>
        /// BootstrapDemo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BundlingTest.Units.BootstrapDemo BootstrapDemo;
        
        /// <summary>
        /// ScriptBundle2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Bundling.Extensions.Controls.ScriptBundle ScriptBundle2;
    }
}
